# -*- coding: utf-8 -*-
"""Conexão_SQL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Deec8bvvAf3Dn-GagNrSKonVwmJ1qsxt
"""

!curl ipecho.net/plain

!pip install mysql-connector-python

import mysql.connector
import pandas as pd

host = '' # endereço do banco externo que quero acessar
user = 'root'
password = ''
database = 'rh1'

connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
) # estas linhas servem para criar a conexão com o banco de dados
cursor = connection.cursor() #criando o cursor para apontar para o banco de dados
query = 'show databases;' # Query ou consulta desejada
cursor.execute(query) # Execução da consulta
result = cursor.fetchall() # armazenando os resultados na variável results
bancos = pd.DataFrame(result,columns=cursor.column_names) # convertendo a variável result em um df pandas chamado tabelas
display(bancos) # exibindo a tabela pandas
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

connection = mysql.connector.connect(
    host=host,
    user=user,
    password=password,
) # estas linhas servem para criar a conexão com a instância
cursor = connection.cursor() #criando o cursor para apontar para a instância
query = 'create database rh' # Query ou consulta desejada
cursor.execute(query) # Execução da consulta
connection.commit()
cursor.close() # fechando o cursor
connection.close() # fechando a conexão

def consulta():
  query = input('Informe a query: ')
  tabela = input('Informe o nme da tabela para armazenar: ')
  connection = mysql.connector.connect(
      host = host,
      user = user,
      password = password,
      database = database
  )
  cursor = connection.cursor()

  try:
    cursor.execute(query)
    result = cursor.fetchall()
    globals()[tabela] = pd.DataFrame(result, columns=cursor.column_names)
    display(globals()[tabela])
  finally:
    cursor.close()
    connection.close()

consulta()