# -*- coding: utf-8 -*-
"""Medidas_de_associacao.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukGDexeZbfLQvg184IhZXtWQzdCP3KvM
"""

import statistics
import numpy as np
from scipy.stats import pearsonr

''' Covariância: Mede a variabilidade conjunta entre duas variáveis.
Valores positivos indicam que ambas variam na mesma direção;
negativos indicam direções opostas.'''

import statistics

x = [1, 2, 3, 4, 5]
y = [1, 2, 3, 1, 2]

covarianca = statistics.covariance(x, y)
print(f'Covariância: {covarianca}')

'''Mede a relação linear entre duas variáveis. Varia entre -1 (corrleçao negativa perfeita)
e +1 (correlação positiva perfeita). Ideal para dados contínuos e normalmente distribuídos'''
'''Suponha que você deseja analisar a relação entre o peso da carga de um caminhão e o consumo
de conbustível.'''

peso_carga = np.array([10, 12, 8, 15, 11]) # x = peso da carga
consumo_combustivel = np.array([250, 280, 320, 270]) # y = consumo de combustível

#cáculo da correlação de Pearson

correlacao_coeficiente, p_valor= pearsonr(x, y)
# correlação = mede a força e a direção da relação linear entre as variáveis
# p-valor testa hipótese para verificar se estão relacionados ou não

print(f'Coeficiente de correlação de Pearson: {correlacao_coeficiente}')
print(f'P-valor: {p_valor}')

alpha = 0.05

#hipótese nula(H0): Não há diferença no consumo de combustpivel
#hipótese alternativa (H1): há diferença no consumo de combustível

#interpretação - significância
if p_valor < alpha:
    print('Rejeitamos a hipótese nula: há diferença no consumo de combustível.')
else:
    print('Não rejeitamos a hipótese nula: não há diferença no consumo de combustível.')