# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13dI3hHOvRqIvAZ40eV9f1T5iD3DiCzhM
"""

'''
O número de petroleiros que chegam a umarefinaria em cada dis ocorre segundo
uma distribuição de Poisson com média de 2 petroleiros por dia. As atuais
instalações podem atender, no máximo, a três petroleiros por dia. se mais de 3
aportarem num dia, o excesso é enviado a outro porto.Qual a probabilidade de
se enviar petroleirossa outro porto num determinado dia?'''

'''
Carros chegam a um lava-carros aleatório e independentemente segundo uma
distribuição de Poisson; a probabilidade de uma chegada é a mesma para qualquer
dois intervalos de tempo de igual comprimento. A taxa média de chegada é de 15
carros por hora. Qual é a probabilidade de que 20 carros ou mais cheguem durante
qualquer hora de operação?
'''